name: Cloudflare Error Monitor

on:
  schedule:
    # Se ejecuta cada 5 minutos exactos de forma perpetua
    - cron: '*/5 * * * *'
  workflow_dispatch: # Te permite picar un botón para probarlo manualmente

jobs:
  check-errors:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código del repositorio
        uses: actions/checkout@v5

      - name: Configurar Node.js
        uses: actions/setup-node@v5
        with:
          node-node: '24'

      - name: Ejecutar script de monitoreo
        env:
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: node monitor.js
